name: Makefile CI

on:
  push:
    branches:
      - main

    tags:
      - v1.*

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build application
      run: make

    - name: Install application
      run: make install
